### ISSUE TITLE
rEFInd detecting OS, not showing correct theme icon

### ISSUE THREAD

**Issue by eureki** [aroman/elementary-on-a-mac#38]
Hi aroman,

Thanks for the in depth guide!
I've been able to install Elementary OS and theme it with [this](https://github.com/andersfischernielsen/rEFInd-minimal-black/blob/master/theme.conf) which has changed the OSX icon but not the Elementary OS icon. I've tried renaming the os_elementary.png file in both the theme directory and efi/boot directories [like you suggested](https://github.com/aroman/freya-on-a-mac/issues/13) but the original blue icon remains. I've also tried deleting all copies of the original icons/os_elementary.png file but rEFInd is still getting it from somewhere.

I've been able to manually display the icon in rEFInd with a _menuentry_ but then can't get the settings right to boot into Elementary OS.

Any ideas?

**Comment by aroman** [comment]
Hmm, that comment is quite old now. At the time rEFInd didn't have native elementary OS detection and icons support, but it should now. I'm gonna close this since I think this is fixed now, but if you have further issues feel free to reopen. Sorry for the late response!
