### ISSUE TITLE
black screen after running from usb

### ISSUE THREAD

**Issue by janvanderkamp** [aroman/elementary-on-a-mac#41]
Hi there,

I got as far as choosing "Try Elementary OS" from the usb, but get a black screen each time. I then tried elementary os 0.3.2, instead and the screen showed this before going black and timing out again:

[     1.934033]  i8042: No controller found
[     1.995551] ACPI PCC probe failed.

Just wondering if anybody here has come across this or has any ideas?  

(MacBook Pro 15-inch, Early 2011, 2.2 ghz core i7)

**Comment by aroman** [comment]
Hi, sorry to hear about your issue.

Would recommend posting on http://elementaryos.stackexchange.com/, as you're much more likely to get support (and quickly) there :-)
