### ISSUE TITLE
rEFInd not appearing startup disk

### ISSUE THREAD

**Issue by Waynekosimoto** [aroman/elementary-on-a-mac#46]
Computer: iMac Mid 2011 running macOS Sierra version 10.12.5 with system integrity protection (SIP) disabled.

When I hold option before the computer starts there was no option for rEFInd. When I go to recovery mode and look at startup disk there is no rEFInd. When I turn on my computer and look at startup disk there is no rEFInd.

When I run the install script this is what happens
```
refind: ./refind-install
Not running as root; attempting to elevate privileges via sudo....
Password:
ShimSource is none
Installing rEFInd on OS X....
Installing rEFInd to the partition mounted at /Volumes/ESP
Found rEFInd installation in /Volumes/ESP/EFI/refind; upgrading it.
Copied rEFInd binary files

Notice: Backed up existing icons directory as icons-backup.
Existing refind.conf file found; copying sample file as refind.conf-sample
to avoid overwriting your customizations.


refind:
```
The only lead that I have is that it looks slightly different than on the refind website in some parts and there is no "Installation has completed successfully". I've done this a couple of times so I don't know if I'm messing things up.

My diskutil list looks like this:
```
/dev/disk0 (internal, physical):

   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macintosh HD            499.2 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *1.4 GB     disk1
   1:                       0xEF                         9.6 MB     disk1s2
```
Thing is I've installed rEFInd before I reinstalled mac. I don't know if there are remnants that are interfering with the process.

I doubt you need this but my mac uses 64-bit EFI implementation
```
refind: ioreg -l -p IODeviceTree | grep firmware-abi

    | |   "firmware-abi" = <"EFI64">
```

**Comment by sdaitzman** [comment]
rEFInd is not typically installed on a new partition, but on your boot partition (Macintosh HD) or, more recently, the EFI partition. Try mounting your EFI partition with the following commands in Terminal:

```
$ sudo mkdir -p /Volumes/ESP
$ sudo mount -t msdos /dev/disk0s1 /Volumes/ESP
```

In Finder, you should then see the ESP (EFI System Partition) mounted. Check what's inside it! If rEEFInd is installed there but is not appearing, it may not be properly blessed. You can find lots of docs on that with `$ man bless`, but let me know what you find in your EFI partition and I can help with that.

**Comment by Waynekosimoto** [comment]
I think I might have messed up a lot of this because I tried mounting it and blessing stuff before this. This is exactly what I did:

```
~: sudo mkdir -p /Volumes/ESP
Password:
~: sudo mount -t msdos /dev/disk0s1/Volumes/ESP
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
~: sudo mount -t msdos /dev/disk0s1 /Volumes/ESP
mount_msdos: /dev/disk0s1: Resource busy
~:
```
I already had the EFI as a device in finder previously.

**Comment by Waynekosimoto** [comment]
![screen shot 101](https://user-images.githubusercontent.com/12769365/32708565-448632de-c7f0-11e7-9b55-7e3eac577fde.png)

**Comment by Waynekosimoto** [comment]
okay so I did
sudo bless --mount /Volumes/ESP --setBoot --file /Volumes/ESP/efi/refind/refind_x64.efi --shortform

**Comment by Waynekosimoto** [comment]
It's good. Didn't press anything after reboot and it launched it.

**Comment by sdaitzman** [comment]
Glad to hear that! Let us know if you have any other questions or issues @Waynekosimoto
